version: "3.0"

services:
  backend:
    build: .
    container_name: mvc-backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=mvc_backend
      - DB_USER=admin
      - DB_PASSWORD=admin
      - SECRET_KEY=examplesecretkey
    volumes:
      - .:/app
    command: /bin/bash -c "./wait-for-it.sh db:3306 -- uvicorn main:app --host 0.0.0.0 --port 8000 --reload"

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: mvc_backend
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
